version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/srs/reverse-proxy/conf:/etc/nginx/conf.d
      - /root/srs/reverse-proxy/vhost:/etc/nginx/vhost.d
      - /root/srs/reverse-proxy/html:/usr/share/nginx/html
      - /root/srs/reverse-proxy/dhparam:/etc/nginx/dhparam
      - /root/srs/reverse-proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes_from:
      - nginx-proxy
    volumes:
      - /root/srs/reverse-proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
